### ISSUE TITLE
Replying through notification does not work

### ISSUE THREAD

**Issue by arainot** [hrubymar10/goofy_swift#3] opened 2018-03-02 14:33 UTC
Hi,

Another bug:

- When I try to reply through a notification badge and click "send" (or press Enter), the message is not sent. It writes the message in the chat box on the main window but does not send the message.

**Comment by hrubymar10** [comment] 2018-03-02 14:43
Please include informations such as which version is affected, OS version, ...

Anyway I can't reproduce it myself in GoofySwift 4.2 in macOS 10.13.4 beta 2.

**Comment by arainot** [comment] 2018-03-02 17:11
I'm on a Mac 10.13.3 with the app 4.2. Maybe I need to restart my Mac, I'll let you know.

**Comment by arainot** [comment] 2018-03-04 14:09
This still happens, not sure how to correctly report it. It worked with Swift 2.x.

**Comment by hrubymar10** [comment] 2018-03-04 14:10
I'll try investigate it.

**Comment by arainot** [comment] 2018-03-04 14:11
Happens with 4.3 Beta 2 and 4.2

**Comment by hrubymar10** [comment] 2018-03-04 14:58
Fixed with e1af585e2756fef8a8a003c06082dfeb5324fc32

After relauch notifications will work.

Closing...

**Closed as completed by hrubymar10** 2018-03-04 14:58 UTC
Labels: bug
